apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050 #other pod that needs multi-client image Pod
      targetPort: 3000
      nodePort: 31515 #access the multi-client image Pod, 30000-32767
  selector:
    component: web
